version: "3.8"
services:
  # front
  memori-front-web:
    build: 
      dockerfile: docker/memori-front/web/Dockerfile
      context: .
    ports:
      - '50001:80'
    depends_on:
      - memori-front-app
    volumes:
      - type: bind
        source: ./memori-front/src
        target: /app/memori-front
    working_dir: /app/memori-front
        
  memori-front-app:
    build: 
      dockerfile: docker/memori-front/app/Dockerfile
      context: .
    ports:
     - "9001:9000"
    volumes:
      - type: bind
        source: ./memori-front/src
        target: /app/memori-front
    working_dir: /app/memori-front

  # batch
  memori-batch-web:
    build: 
      dockerfile: docker/memori-batch/web/Dockerfile
      context: .
    volumes:
      - type: bind
        source: ./memori-batch/src
        target: /app/memori-batch
    depends_on:
      - memori-batch-app
    working_dir: /app/memori-batch

  memori-batch-app:
    build: 
      dockerfile: docker/memori-batch/app/Dockerfile
      context: .
    volumes:
      - type: bind
        source: ./memori-batch/src
        target: /app/memori-batch
    working_dir: /app/memori-batch

  # db
  db:
    build:
      dockerfile: docker/memori-front/db/Dockerfile
      context: .
    ports:
      - 33062:3306
    environment:
      MYSQL_DATABASE: memori
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user 
      MYSQL_USER_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - type: volume
        source: mysql-volume
        target: /var/lib/mysql
      - type: bind
        source: ./docker/memori-front/db/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
        
volumes:
  mysql-volume: